### ISSUE TITLE
failing unit tests - help wanted?

### ISSUE THREAD

**Issue by 304NotModified** [GeReV/NSoup#5]
> NOTE: (2013-07-10) In the last few months I've been struggling with a few tests crashing for some reason I cannot isolate. I've pushed the latest version of the source code, and if anyone can help solve those issues it would greatly help this project.

Still interested in some help on this?

**Comment by GeReV** [comment]
@304NotModified, absolutely, any help would be appreciated!
I haven't been actively working on this project for a while now, though. It's far behind jsoup at this point.

**Comment by 304NotModified** [comment]
oops, forgot about this, but it's done -> #11
